//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace infrastructure.i18n.user {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserResponseMessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserResponseMessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("infrastructure.i18n.user.UserResponseMessagesResource", typeof(UserResponseMessagesResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me should not be greater than 300 characters..
        /// </summary>
        public static string aboutme_not_in_range {
            get {
                return ResourceManager.GetString("aboutme_not_in_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age not in the correct format.
        /// </summary>
        public static string age_not_in_range {
            get {
                return ResourceManager.GetString("age_not_in_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload image is greater than 10 MB, please upload smaller size. .
        /// </summary>
        public static string avatar_too_big {
            get {
                return ResourceManager.GetString("avatar_too_big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes have been saved successfully.
        /// </summary>
        public static string changes_saved {
            get {
                return ResourceManager.GetString("changes_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country should be between 2 y 50 characters.
        /// </summary>
        public static string country_not_in_range {
            get {
                return ResourceManager.GetString("country_not_in_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid crop area.
        /// </summary>
        public static string crop_area_invalid {
            get {
                return ResourceManager.GetString("crop_area_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is empty.
        /// </summary>
        public static string current_password_empty {
            get {
                return ResourceManager.GetString("current_password_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password should be between 6 y 30 characters.
        /// </summary>
        public static string current_password_not_in_range {
            get {
                return ResourceManager.GetString("current_password_not_in_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another user already registered this email address.
        /// </summary>
        public static string email_already_used {
            get {
                return ResourceManager.GetString("email_already_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the link has expired .
        /// </summary>
        public static string email_change_fail {
            get {
                return ResourceManager.GetString("email_change_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to your account and request it again.
        /// </summary>
        public static string email_change_fail_desc {
            get {
                return ResourceManager.GetString("email_change_fail_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s done!.
        /// </summary>
        public static string email_change_ok {
            get {
                return ResourceManager.GetString("email_change_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new email has been activated.
        /// </summary>
        public static string email_change_ok_desc {
            get {
                return ResourceManager.GetString("email_change_ok_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account exists with this email address.
        /// </summary>
        public static string email_does_not_exists {
            get {
                return ResourceManager.GetString("email_does_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone has already used this email to register with us..
        /// </summary>
        public static string email_duplicated {
            get {
                return ResourceManager.GetString("email_duplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is taken by another user. Switching back to:.
        /// </summary>
        public static string email_duplicated_switch_to {
            get {
                return ResourceManager.GetString("email_duplicated_switch_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is empty.
        /// </summary>
        public static string email_empty {
            get {
                return ResourceManager.GetString("email_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format is incorrect.
        /// </summary>
        public static string email_invalid {
            get {
                return ResourceManager.GetString("email_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t change your email as you are not logged in.
        /// </summary>
        public static string email_login_to_apply_change {
            get {
                return ResourceManager.GetString("email_login_to_apply_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Login to the system by clicking on the &quot;Login&quot; button.
        /// </summary>
        public static string email_login_to_apply_change_desc1 {
            get {
                return ResourceManager.GetString("email_login_to_apply_change_desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Open your email inbox and got to the message we sent you..
        /// </summary>
        public static string email_login_to_apply_change_desc2 {
            get {
                return ResourceManager.GetString("email_login_to_apply_change_desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Click on the link provided within the email.
        /// </summary>
        public static string email_login_to_apply_change_desc3 {
            get {
                return ResourceManager.GetString("email_login_to_apply_change_desc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *If you are still unable to omplete your request please contact &lt;a href=&quot;mailto:putoamo.es@gmail.com&quot; title=&quot;Sent us an email&quot;&gt;putoamo.es@gmail.com&lt;/a&gt;.
        /// </summary>
        public static string email_login_to_apply_change_idiot_html {
            get {
                return ResourceManager.GetString("email_login_to_apply_change_idiot_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must be netween 6 y 250 characters..
        /// </summary>
        public static string email_not_in_range {
            get {
                return ResourceManager.GetString("email_not_in_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid..
        /// </summary>
        public static string email_not_valid {
            get {
                return ResourceManager.GetString("email_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email or Password..
        /// </summary>
        public static string email_password_incorrect {
            get {
                return ResourceManager.GetString("email_password_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email change request has been canceled successfully..
        /// </summary>
        public static string email_request_cancelled {
            get {
                return ResourceManager.GetString("email_request_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New email is the same as the current one..
        /// </summary>
        public static string email_requested_same_as_current {
            get {
                return ResourceManager.GetString("email_requested_same_as_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email saved successfully..
        /// </summary>
        public static string email_saved {
            get {
                return ResourceManager.GetString("email_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We felt a great disturbance in the force, as if millions of lines of code suddenly cried out in terror and were suddenly silenced. We fear something terrible has happened. Looking into it..
        /// </summary>
        public static string error_wierd_shit_going_on {
            get {
                return ResourceManager.GetString("error_wierd_shit_going_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name should be between 2 y 80 characters.
        /// </summary>
        public static string firstname_not_in_range {
            get {
                return ResourceManager.GetString("firstname_not_in_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key.
        /// </summary>
        public static string invalid_key {
            get {
                return ResourceManager.GetString("invalid_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name should be between 2 y 80 characters.
        /// </summary>
        public static string lastname_not_in_range {
            get {
                return ResourceManager.GetString("lastname_not_in_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passowrd is empty.
        /// </summary>
        public static string new_password_empty {
            get {
                return ResourceManager.GetString("new_password_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Contraseña tiene que tener entre 6 y 30 caracteres.
        /// </summary>
        public static string new_password_not_in_range {
            get {
                return ResourceManager.GetString("new_password_not_in_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Nueva Contraseña es muy debil.
        /// </summary>
        public static string new_password_too_weak {
            get {
                return ResourceManager.GetString("new_password_too_weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes made.
        /// </summary>
        public static string no_changes_made {
            get {
                return ResourceManager.GetString("no_changes_made", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si no deseas aceptar los permisos puedes darte de alta con nuestro sistema usando este formulario.
        /// </summary>
        public static string oauth_alternative_message {
            get {
                return ResourceManager.GetString("oauth_alternative_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string oauth_email {
            get {
                return ResourceManager.GetString("oauth_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo necesitamos para identificarte y informarte..
        /// </summary>
        public static string oauth_facebook_email {
            get {
                return ResourceManager.GetString("oauth_facebook_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sirve para compartir tu votos en forma automatica, nunca publicaremos en tu muro sin tu previo permiso..
        /// </summary>
        public static string oauth_facebook_wall {
            get {
                return ResourceManager.GetString("oauth_facebook_wall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El login que intentas añadir ya esta asociado con otra cuenta.
        /// </summary>
        public static string oauth_login_with_other_user {
            get {
                return ResourceManager.GetString("oauth_login_with_other_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fuimos capaces de darte de alta.
        /// </summary>
        public static string oauth_permission_title {
            get {
                return ResourceManager.GetString("oauth_permission_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parece que has rechazado los permisos que pedimos al Facebook.
        /// </summary>
        public static string oauth_permissions_facebook_message {
            get {
                return ResourceManager.GetString("oauth_permissions_facebook_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intenta otra vez.
        /// </summary>
        public static string oauth_try_again_button {
            get {
                return ResourceManager.GetString("oauth_try_again_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicar en tu muro.
        /// </summary>
        public static string oauth_wall_post {
            get {
                return ResourceManager.GetString("oauth_wall_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud del cambio de la contraseña ha caducado. Intentalo de nuevo!.
        /// </summary>
        public static string password_change_expired {
            get {
                return ResourceManager.GetString("password_change_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been changed  successfully..
        /// </summary>
        public static string password_changed {
            get {
                return ResourceManager.GetString("password_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match..
        /// </summary>
        public static string password_doesnt_match {
            get {
                return ResourceManager.GetString("password_doesnt_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is empty..
        /// </summary>
        public static string password_empty {
            get {
                return ResourceManager.GetString("password_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is incorrect..
        /// </summary>
        public static string password_incorrect {
            get {
                return ResourceManager.GetString("password_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current password doesn&apos;t match..
        /// </summary>
        public static string password_no_match {
            get {
                return ResourceManager.GetString("password_no_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be bewteen 6 and 30 characters..
        /// </summary>
        public static string password_not_in_range {
            get {
                return ResourceManager.GetString("password_not_in_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce la Contraseña para guardar los cambios..
        /// </summary>
        public static string password_renter {
            get {
                return ResourceManager.GetString("password_renter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too weak..
        /// </summary>
        public static string password_weak {
            get {
                return ResourceManager.GetString("password_weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile saved successfully..
        /// </summary>
        public static string profile_saved {
            get {
                return ResourceManager.GetString("profile_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated password doesn&apos;t match..
        /// </summary>
        public static string repeat_new_password_doesnt_match {
            get {
                return ResourceManager.GetString("repeat_new_password_doesnt_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated password is empty..
        /// </summary>
        public static string repeat_new_password_empty {
            get {
                return ResourceManager.GetString("repeat_new_password_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated password should be bewteen 6 and 30 characters..
        /// </summary>
        public static string repeat_new_password_not_in_range {
            get {
                return ResourceManager.GetString("repeat_new_password_not_in_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles is too long. Value should be between 3 and 100 characters.
        /// </summary>
        public static string roles_not_in_range {
            get {
                return ResourceManager.GetString("roles_not_in_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error. We have sent an email to our coding monkeys to fix it....
        /// </summary>
        public static string unexpected_error {
            get {
                return ResourceManager.GetString("unexpected_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been created..
        /// </summary>
        public static string user_created {
            get {
                return ResourceManager.GetString("user_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user.
        /// </summary>
        public static string user_id_invalid {
            get {
                return ResourceManager.GetString("user_id_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been saved successfully..
        /// </summary>
        public static string user_saved {
            get {
                return ResourceManager.GetString("user_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is empty..
        /// </summary>
        public static string username_empty {
            get {
                return ResourceManager.GetString("username_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can&apos;t be empty or contain spaces..
        /// </summary>
        public static string username_empty_or_spaces {
            get {
                return ResourceManager.GetString("username_empty_or_spaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username contains spaces..
        /// </summary>
        public static string username_has_spaces {
            get {
                return ResourceManager.GetString("username_has_spaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is not available..
        /// </summary>
        public static string username_not_available {
            get {
                return ResourceManager.GetString("username_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is too short..
        /// </summary>
        public static string username_not_in_range {
            get {
                return ResourceManager.GetString("username_not_in_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username saved successfully..
        /// </summary>
        public static string username_saved {
            get {
                return ResourceManager.GetString("username_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated password is empty..
        /// </summary>
        public static string vpassword_empty {
            get {
                return ResourceManager.GetString("vpassword_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dirección Web tiene que tener entre 2 y 250 caracteres.
        /// </summary>
        public static string website_not_in_range {
            get {
                return ResourceManager.GetString("website_not_in_range", resourceCulture);
            }
        }
    }
}
